# Generated by Django 5.0.2 on 2024-09-16 15:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identification_type', models.CharField(max_length=50)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(max_length=20)),
                ('ethnic_group', models.CharField(max_length=50)),
                ('disability', models.CharField(max_length=50)),
                ('phone_number', models.CharField(max_length=20)),
                ('highest_education_level', models.CharField(max_length=50)),
                ('company_type', models.CharField(max_length=100)),
                ('company_name', models.CharField(max_length=255)),
                ('company_nit', models.CharField(max_length=50)),
                ('previous_business', models.CharField(max_length=10)),
                ('operation_start_year', models.DateField(blank=True, null=True)),
                ('registered_in_ccc', models.CharField(max_length=255)),
                ('main_office_department', models.CharField(max_length=100)),
                ('main_office_municipality', models.CharField(max_length=100)),
                ('business_sector', models.CharField(max_length=100)),
                ('product_type', models.CharField(max_length=100)),
                ('client_focus', models.CharField(max_length=100)),
                ('market_reach', models.CharField(max_length=100)),
                ('business_size', models.CharField(max_length=100)),
                ('data_consent', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Perfil de Usuario',
                'verbose_name_plural': 'Perfiles de Usuarios',
            },
        ),
    ]
