# Generated by Django 5.0.2 on 2024-08-08 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_user_groups_alter_user_user_permissions'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='username',
            new_name='document',
        ),
    ]
