# Generated by Django 5.0.2 on 2024-08-29 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_user_description_user_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='description',
        ),
        migrations.RemoveField(
            model_name='user',
            name='rating',
        ),
    ]
