# Generated by Django 5.0.2 on 2024-09-17 21:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0001_initial'),
        ('users', '0002_userprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfileProxy',
            fields=[
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('users.userprofile',),
        ),
    ]
