# Generated by Django 5.0.2 on 2024-02-25 23:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0006_completedform_delete_useranswer'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='question',
            options={},
        ),
        migrations.RemoveField(
            model_name='question',
            name='order',
        ),
    ]
