# Generated by Django 5.0.2 on 2024-02-26 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0007_alter_question_options_remove_question_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='sub_category',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
