# Generated by Django 5.0.2 on 2024-02-28 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0009_category_alter_question_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='category',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
