# Generated by Django 5.0.2 on 2024-02-28 02:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0013_alter_diagnosticlevel_unique_together_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CategoryDiagnosis',
            new_name='CategoryDiagnostics',
        ),
        migrations.RenameModel(
            old_name='Diagnosis',
            new_name='Diagnostics',
        ),
        migrations.RenameField(
            model_name='categorydiagnostics',
            old_name='diagnosis',
            new_name='diagnostics',
        ),
        migrations.RenameField(
            model_name='diagnosticlevel',
            old_name='category_diagnosis',
            new_name='category_diagnostics',
        ),
        migrations.AlterUniqueTogether(
            name='categorydiagnostics',
            unique_together={('category', 'diagnostics')},
        ),
    ]
