# Generated by Django 5.0.2 on 2024-02-28 02:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0014_rename_categorydiagnosis_categorydiagnostics_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='diagnostics',
            options={'verbose_name_plural': 'Diagnostics'},
        ),
    ]
