# Generated by Django 5.0.2 on 2024-02-28 17:03

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0015_alter_diagnostics_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diagnosticlevel',
            name='description',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
