# Generated by Django 5.0.2 on 2024-02-28 17:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0016_alter_diagnosticlevel_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='form',
            name='diagnostics',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='form', to='forms.diagnostics'),
        ),
    ]
