# Generated by Django 5.0.2 on 2024-02-28 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0017_form_diagnostics'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='diagnosticlevel',
            options={'ordering': ['id']},
        ),
        migrations.AlterField(
            model_name='diagnosticlevel',
            name='level',
            field=models.IntegerField(),
        ),
    ]
