# Generated by Django 5.0.2 on 2024-02-28 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0018_alter_diagnosticlevel_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='diagnosticlevel',
            options={},
        ),
        migrations.AlterModelOptions(
            name='form',
            options={'ordering': ['id']},
        ),
    ]
