# Generated by Django 5.0.2 on 2024-02-28 19:01

import ckeditor.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0019_alter_diagnosticlevel_options_alter_form_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiagnosticDescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', ckeditor.fields.RichTextField()),
                ('level_diagnostics', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Descrption', to='forms.diagnosticlevel')),
            ],
        ),
    ]
