# Generated by Django 5.0.2 on 2024-02-28 19:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0020_diagnosticdescription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diagnosticdescription',
            name='level_diagnostics',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='descriptions', to='forms.diagnosticlevel'),
        ),
    ]
