# Generated by Django 5.0.2 on 2024-02-28 20:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0021_alter_diagnosticdescription_level_diagnostics'),
    ]

    operations = [
        migrations.RenameField(
            model_name='diagnosticdescription',
            old_name='level_diagnostics',
            new_name='levels',
        ),
        migrations.RenameField(
            model_name='diagnosticdescription',
            old_name='description',
            new_name='text',
        ),
        migrations.RemoveField(
            model_name='diagnosticlevel',
            name='description',
        ),
    ]
