# Generated by Django 5.0.2 on 2024-02-28 20:50

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0022_rename_level_diagnostics_diagnosticdescription_levels_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='diagnosticlevel',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='DiagnosticDescription',
        ),
    ]
