# Generated by Django 5.0.2 on 2024-02-28 23:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0023_diagnosticlevel_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diagnosticlevel',
            name='category_diagnostics',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='levels', to='forms.category'),
        ),
        migrations.RemoveField(
            model_name='form',
            name='diagnostics',
        ),
        migrations.AlterModelOptions(
            name='form',
            options={},
        ),
        migrations.DeleteModel(
            name='CategoryDiagnostics',
        ),
        migrations.DeleteModel(
            name='Diagnostics',
        ),
    ]
