# Generated by Django 5.0.2 on 2024-02-28 23:48

import ckeditor.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0024_alter_diagnosticlevel_category_diagnostics_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiagnosticPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('level_diagnostics', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='levels', to='forms.diagnosticlevel')),
            ],
        ),
    ]
