# Generated by Django 5.0.2 on 2024-02-28 23:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0025_diagnosticplan'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diagnosticlevel',
            name='description',
        ),
    ]
