# Generated by Django 5.0.2 on 2024-03-20 21:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0027_alter_completedform_form_title_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='completedform',
            name='form_title',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='completedform',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='completed_forms', to=settings.AUTH_USER_MODEL),
        ),
    ]
