# Generated by Django 5.0.2 on 2024-03-20 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0028_alter_completedform_form_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='completedform',
            name='form_title',
            field=models.CharField(editable=False, max_length=255),
        ),
    ]
