# Generated by Django 5.0.2 on 2024-04-01 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0031_alter_completedform_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='completedform',
            name='email',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
