# Generated by Django 5.0.2 on 2024-04-03 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0032_completedform_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='text',
            field=models.CharField(max_length=510),
        ),
    ]
