# Generated by Django 4.2.13 on 2024-05-31 04:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0034_question_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='order',
        ),
    ]
