# Generated by Django 4.2.13 on 2024-05-31 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0035_remove_question_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='form',
            options={'ordering': ['title']},
        ),
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ['order']},
        ),
        migrations.AddField(
            model_name='question',
            name='order',
            field=models.IntegerField(default=0),
        ),
    ]
