# Generated by Django 4.2.13 on 2024-05-31 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0037_alter_question_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='form',
            options={},
        ),
        migrations.AlterModelOptions(
            name='question',
            options={},
        ),
        migrations.RemoveField(
            model_name='question',
            name='order',
        ),
    ]
