# Generated by Django 5.0.2 on 2024-06-03 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0043_alter_question_options_question_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='completedform',
            name='email',
            field=models.EmailField(blank=True, max_length=255, null=True),
        ),
    ]
