# Generated by Django 5.0.2 on 2024-07-31 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0045_completedformproxy'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='completedformproxy',
            options={'verbose_name': 'Completed Form Download', 'verbose_name_plural': 'Descarga la Base de Datos Completa'},
        ),
    ]
