# Generated by Django 5.0.2 on 2024-08-30 21:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0045_completedformproxy_alter_category_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='completedform',
            options={'verbose_name': 'Formulario completado', 'verbose_name_plural': 'Formularios completados'},
        ),
        migrations.AlterModelOptions(
            name='completedformproxy',
            options={'verbose_name': 'Descarga la base de datos completa', 'verbose_name_plural': 'Descarga la base de datos completa'},
        ),
    ]
