# Generated by Django 5.0.2 on 2024-07-31 20:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0046_alter_completedformproxy_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Categoría', 'verbose_name_plural': 'Categorías'},
        ),
        migrations.AlterModelOptions(
            name='completedform',
            options={'verbose_name': 'Formulario Completado', 'verbose_name_plural': 'Formularios Completados'},
        ),
        migrations.AlterModelOptions(
            name='completedformproxy',
            options={'verbose_name': 'Descarga la Base de Datos Completa', 'verbose_name_plural': 'Descarga la Base de Datos Completa'},
        ),
        migrations.AlterModelOptions(
            name='form',
            options={'verbose_name': 'Formulario', 'verbose_name_plural': 'Formularios'},
        ),
    ]
