# Generated by Django 5.0.2 on 2024-08-23 23:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0047_alter_category_options_alter_completedform_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan', models.TextField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forms.category')),
                ('completed_form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_plans', to='forms.completedform')),
            ],
        ),
    ]
