# Generated by Django 5.0.2 on 2024-08-23 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0048_workplan'),
    ]

    operations = [
        migrations.AddField(
            model_name='workplan',
            name='identification_number',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
