# Generated by Django 5.0.2 on 2024-08-25 20:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0049_workplan_identification_number'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WorkPlan',
        ),
    ]
