# Generated by Django 5.0.2 on 2024-09-12 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Availability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mentor_name', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('link', models.URLField()),
                ('rating', models.DecimalField(decimal_places=2, default=0.0, max_digits=3)),
            ],
            options={
                'verbose_name': 'Citas disponibles',
                'verbose_name_plural': 'Citas disponibles',
            },
        ),
        migrations.CreateModel(
            name='Mentoring',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_mentor', models.BooleanField(default=False)),
                ('is_apprentice', models.BooleanField(default=False)),
                ('about', models.TextField(blank=True, null=True)),
                ('rating', models.DecimalField(decimal_places=2, default=0.0, max_digits=3)),
                ('total_ratings', models.PositiveIntegerField(default=0)),
                ('ratings_sum', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Mentores/Aprendices',
                'verbose_name_plural': 'Mentores/Aprendices',
            },
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('is_confirmed', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Sesión',
                'verbose_name_plural': 'Sesiones',
                'ordering': ['availability__date'],
            },
        ),
    ]
