# Generated by Django 5.0.2 on 2024-08-06 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mentoring', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mentee',
            name='user',
        ),
        migrations.RemoveField(
            model_name='mentor',
            name='user',
        ),
        migrations.RemoveField(
            model_name='mentorshipsession',
            name='mentee',
        ),
        migrations.RemoveField(
            model_name='mentorshipsession',
            name='mentor',
        ),
        migrations.RemoveField(
            model_name='user',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='user',
            name='user_permissions',
        ),
        migrations.DeleteModel(
            name='Availability',
        ),
        migrations.DeleteModel(
            name='Mentee',
        ),
        migrations.DeleteModel(
            name='Mentor',
        ),
        migrations.DeleteModel(
            name='MentorshipSession',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
