# Generated by Django 5.0.2 on 2024-09-12 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentoring', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mentoring',
            name='is_apprentice',
            field=models.BooleanField(default=True),
        ),
    ]
