# Generated by Django 5.0.2 on 2024-08-11 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentoring', '0004_alter_mentoring_options_availability_session'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='availability',
            name='day_of_week',
        ),
        migrations.AddField(
            model_name='availability',
            name='date',
            field=models.DateField(default='2024-08-12'),
            preserve_default=False,
        ),
    ]
