# Generated by Django 5.0.2 on 2024-08-12 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentoring', '0005_remove_availability_day_of_week_availability_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='availability',
            name='mentor_name',
            field=models.CharField(default='Esteban Gomez Hernandez', max_length=255),
            preserve_default=False,
        ),
    ]
