# Generated by Django 5.0.2 on 2024-08-14 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mentoring', '0006_availability_mentor_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='session',
            options={'ordering': ['availability__date']},
        ),
    ]
