# Generated by Django 5.0.2 on 2024-08-29 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentoring', '0007_alter_session_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='mentoring',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mentoring',
            name='rating',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=3, null=True),
        ),
        migrations.AddField(
            model_name='mentoring',
            name='ratings_sum',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='mentoring',
            name='total_ratings',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='mentoring',
            name='is_apprentice',
            field=models.BooleanField(default=False),
        ),
    ]
