# Generated by Django 5.0.2 on 2024-08-29 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0045_completedformproxy_alter_category_options_and_more'),
        ('mentoring', '0008_mentoring_description_mentoring_rating_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mentoring',
            name='categories',
            field=models.ManyToManyField(related_name='mentors', to='forms.category'),
        ),
        migrations.AlterField(
            model_name='mentoring',
            name='rating',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=3),
        ),
        migrations.AlterField(
            model_name='mentoring',
            name='ratings_sum',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='mentoring',
            name='total_ratings',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
