# Generated by Django 5.0.2 on 2024-08-30 21:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mentoring', '0009_mentoring_categories_alter_mentoring_rating_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mentoring',
            old_name='description',
            new_name='about',
        ),
    ]
