# Generated by Django 5.0.2 on 2024-08-30 21:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mentoring', '0010_rename_description_mentoring_about'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='availability',
            options={'verbose_name': 'Citas disponibles', 'verbose_name_plural': 'Citas disponibles'},
        ),
        migrations.AlterModelOptions(
            name='mentoring',
            options={'verbose_name': 'Mentores/Aprendices', 'verbose_name_plural': 'Mentores/Aprendices'},
        ),
        migrations.AlterModelOptions(
            name='session',
            options={'ordering': ['availability__date'], 'verbose_name': 'Sesión', 'verbose_name_plural': 'Sesiones'},
        ),
    ]
