# Generated by Django 5.0.2 on 2024-08-30 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentoring', '0011_alter_availability_options_alter_mentoring_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='availability',
            name='about',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='availability',
            name='rating',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=3),
        ),
        migrations.AddField(
            model_name='availability',
            name='ratings_sum',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
