# Generated by Django 5.0.2 on 2024-08-30 23:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mentoring', '0012_availability_about_availability_rating_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='availability',
            name='about',
        ),
        migrations.RemoveField(
            model_name='availability',
            name='mentor_name',
        ),
        migrations.RemoveField(
            model_name='availability',
            name='rating',
        ),
        migrations.RemoveField(
            model_name='availability',
            name='ratings_sum',
        ),
    ]
