# Generated by Django 5.0.2 on 2024-08-30 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentoring', '0014_availability_mentor_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='availability',
            name='about',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='availability',
            name='rating',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=3),
        ),
    ]
