# Generated by Django 5.0.2 on 2024-09-06 00:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mentoring', '0015_availability_about_availability_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='availability',
            name='about',
        ),
    ]
